########################################
# XaeroFlux Core Configuration (TOML)
########################################
version = 1                                                                    # Version of the XaeroFlux software
name = "xaeroflux"                                                             # Name of this node
description = "A distributed event processing node for the XaeroFlux network."

# ————————————————————————————
# Append-Only File (AOF) settings
# ————————————————————————————

[aof]
# enable or disable the AOF layer entirely
enabled = true

# where to write your append-only log
file_path = "data/xaeroflux.aof"

# how often (in ms) to flush buffered events to disk
flush_interval_ms = 1000

# rotate (or refuse writes) once the AOF grows beyond this size
max_size_bytes = 1073741824 # 1 GiB

# compression codec for on-disk event blobs (none, lz4, zstd, etc.)
compression = "lz4"

# when you hit max_size_bytes: "rotate", "truncate", or "fail"
retention_policy = "rotate"

# how big each write buffer is (also your mmap chunk size)
buffer_size = 16384


# ————————————————————————————
# Per-module threading settings
# (shared by AOF, Merkle indexer, etc.)
# ————————————————————————————

[aof.threads]
# how many worker threads to spawn
num_worker_threads = 4

# whether to pin those threads to OS cores
pin_threads = false

# Where on disk to store your RocksDB data, WALs, and Merkle files.
[storage]
data_dir = "/var/lib/xaeroflux/data"
wal_dir = "/var/lib/xaeroflux/wal"
merkle_index_dir = "/var/lib/xaeroflux/merkle"
create_if_missing = true
max_open_files = 512

# Merkle‑tree paging & flushing
[merkle]
page_size = 8_192         # bytes per page mmap'd
flush_interval_ms = 1_000 # how often to fsync pages
max_nodes_per_page = 256  # how many tree‑nodes per page file

# Peer‑to‑Peer (libp2p / DHT / CRDT) settings
[p2p]
listen_address = "/ip4/0.0.0.0/tcp/4001"
bootstrap_nodes = ["node1.example.com:4001", "node2.example.com:4001"]
enable_mdns = true
crdt_strategy = "lww"                                                  # last‑write‑wins merge
max_msg_size_bytes = 1_048_576                                         # 1 MiB

# Per‑EventType buffering and batching
[event_buffers]
# You can add one table for each EventType you support:
[event_buffers.ApplicationEvent]
capacity = 1024  # channel capacity
batch_size = 64  # how many events to pull before processing
timeout_ms = 500 # max wait before forcing a batch

[event_buffers.SystemEvent]
capacity = 512
batch_size = 32
timeout_ms = 200

[event_buffers.NetworkEvent]
capacity = 512
batch_size = 32
timeout_ms = 200

[event_buffers.StorageEvent]
capacity = 512
batch_size = 32
timeout_ms = 200

# Thread‑pool / event‑loop tuning
[threads]
num_worker_threads = 4 # e.g. one per major subsystem
pin_threads = true     # bind each thread to its own core

# Logging / diagnostics
[logging]
level = "info"                  # trace | debug | info | warn | error
file = "/var/log/xaeroflux.log"
