[package]
name = "xaeroflux"
version = "0.2.0-m3"
edition = "2024"

[dependencies]
xaeroflux-core = { path = "../xaeroflux-core" }
xaeroflux-actors = { path = "../xaeroflux-actors" }
xaeroflux-macros = { path = "../xaeroflux-macros" }