[package]
name = "xaeroflux"
version = "0.1.0-m3.1"
edition = "2024"

[dependencies]
xaeroflux-core = { path = "../xaeroflux-core" }
xaeroflux-actors = { path = "../xaeroflux-actors" }
xaeroflux-macros = { path = "../xaeroflux-macros" }