[package]
name = "xaeroflux"
version = "0.2.0-m3"
edition     = "2024"
description = "EXPERIMENTAL: actor layer for xaeroflux"
categories = ["database", "database-implementations"]
keywords = ["unstable", "draft", "experimental"]
authors = ["ricky.nj@gmail.com"]
license = "MPL-2.0"
documentation = "https://github.com/block-xaero/xaeroflux.git"
repository = "https://github.com/block-xaero/xaeroflux.git"
homepage = "https://blockxaero.io"
readme = "README.md"

[dependencies]
xaeroflux-core = "0.2.0-m3"
xaeroflux-actors =  "0.2.0-m3"
xaeroflux-macros =  "0.2.0-m3"